[package]
name = "advent-of-code-2020"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
advent-of-code-common = { path = "../common" }
lazy_static.workspace = true
regex.workspace = true
