name: Scala 3 CI

on:
  push:
    branches: [ "master" ]
    paths:
      - 'scala3/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'scala3/**'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: sbt/setup-sbt@v1

      - name: Run tests
        working-directory: ./scala3
        run: sbt test
