name: Scala 2 CI

on:
  push:
    branches: [ "master" ]
    paths:
      - 'scala2/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'scala2/**'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: graalvm/setup-graalvm@v1
      with:
        java-version: '21'
        distribution: 'graalvm'
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - uses: sbt/setup-sbt@v1
     
    - name: Install Z3
      run: sudo apt-get update && sudo apt-get install -y z3

    - name: Run tests
      working-directory: ./scala2
      run: sbt test
